### ISSUE TITLE
Is this useable?

### ISSUE THREAD

**Issue by Epictek** [nim-lang/langserver#1]
Also why the lack of read me, would be useful as to show the status of the project.

**Comment by zah** [comment]
Not yet - a readme will be added once a basic version is ready for use.

Don't be misled by the lack of progress in this repo. Currently, progress is being done in the JSON-RPC library that will be used for implementing the language server protocol:

https://github.com/status-im/nim-eth-rpc/issues/15

**Comment by QuinnFreedman** [comment]
I've found a lot of the nim language plugins to be pretty buggy. I think this could be a huge win for all of them if it gets finished. Looking forward to it!

**Comment by PMunch** [comment]
Just if anyone comes across this, Nim has a language server implemented in https://github.com/PMunch/nimlsp
