### ISSUE TITLE
Symlink needed re: nimlsp

### ISSUE THREAD

**Issue by michaelsbradleyjr** [nim-lang/langserver#11]
Per https://github.com/status-im/nim-codex/pull/80 I learned about this repo today (have been using nimlsp for awhile) and decided to give it a shot. So far so good. 😄 

One thing I needed to do is put a symlink in my `PATH` so that `nimlsp` resolves to `~/.nimble/bin/nimlangserver`.

Is it time yet to open a PR in [emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode) adding support for `nimlangserver`, and/or do you think it's worthwhile to mention in the README that at present a workaround (e.g. using a symlink) is needed?

**Comment by yyoncho** [comment]
> Is it time yet to open a PR in [emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode) adding support for `nimlangserver`, and/or do you think it's worthwhile to mention in the README that at present a workaround (e.g. using a symlink) is needed?

I will handle that later today + adding the corresponding defcustom mapping (I am also the lsp-mode maintainer).
