### ISSUE TITLE
 nimlangserver-windows-amd64.tar.gz -> .zip & 1 redundand file

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/langserver#112]
in
https://github.com/nim-lang/langserver/releases
    --> assets
"nimlangserver-windows-amd64.tar.gz"
contains the 2 identical files :
    nimlangserver.exe
    nimlangserver

could please the redundand file "nimlangserver"
be removed form "nimlangserver-windows-amd64.tar.gz"
and this .tar.gz be provided as .zip , additionally to or
instead of the .tar.gz , because .tar.gz is uncommon
and not native on win10 .

**Comment by nickysn** [comment]
Fixed both issues.
