### ISSUE TITLE
Can't build with v1.6.6

### ISSUE THREAD

**Issue by Clonkk** [nim-lang/langserver#14]
I've firs tried ``nimble install nimlangserver`` and it fails.

I then cloned this repo on the master branch and building (``nimble build``) the repo and it also fails. 

```
/home/rcaillaud/Workspace/localws/langserver/suggestapi.nim(198, 103) template/generic instantiation of `async` from here
/home/rcaillaud/Workspace/localws/langserver/suggestapi.nim(200, 22) Error: type mismatch: got <register: bool, nonBlockingWrite: bool>
but expected one of:
proc createPipe(size = 65536; register = true): AsyncPipe
  first type mismatch at position: 2
  unknown named parameter: nonBlockingWrite

expression: createPipe(register = true, nonBlockingWrite = false)
       Tip: 235 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: nimlangserver
        ... Execution failed with exit code 1
```
Looking at the path list : 

> 
> ... Command: /home/rcaillaud/.nimble/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.0 
> **--path:'/home/rcaillaud/.nimble/pkgs/asynctools-#non-blocking'** --path:'/home/rcaillaud/.nimble/pkgs/json_rpc-#notif-changes' 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/nimcrypto-0.5.4 --path:/home/rcaillaud/.nimble
> /pkgs/stint-0.0.1 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 --path:/home
> /rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble
> /pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/chronicles-0.10.2 --path:/home
> /rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble
> /pkgs/json_serialization-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/serialization-0.1.0 --path:/home/rcaillaud/.nimble
> /pkgs/faststreams-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home
> /rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 --path:/home/rcaillaud/.nimble
> /pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 --path:/home
> /rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble
> /pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home
> /rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/news-#status' --path:/home/rcaillaud/.nimble/pkgs/websock-0.1.0 
> --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble
> /pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home
> /rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0
>  --path:/home/rcaillaud/.nimble/pkgs/chronicles-0.10.2 --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble
> /pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/json_serialization-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/serialization-0.1.0
>  --path:/home/rcaillaud/.nimble/pkgs/faststreams-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble
> /pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble
> /pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home
> /rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble
> /pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud
> /.nimble/pkgs/asynctest-0.3.1 --path:/home/rcaillaud/.nimble/pkgs/nimcrypto-0.5.4 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 
> --path:/home/rcaillaud/.nimble/pkgs/zlib-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 **--path:/home/rcaillaud/.nimble
> /pkgs/asynctools-0.1.1** --path:/home/rcaillaud/.nimble/pkgs/faststreams-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 
> --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble
> /pkgs/chronos-3.0.11 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home
> /rcaillaud/.nimble/pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head'
>  --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/json_serialization-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/serialization-0.1.0 
> --path:/home/rcaillaud/.nimble/pkgs/faststreams-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/with-0.4.0 --path:/home/rcaillaud/.nimble/pkgs/itertools-0.4.0
>  --path:/home/rcaillaud/.nimble/pkgs/chronicles-0.10.2 --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/json_serialization-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/serialization-0.1.0 
> --path:/home/rcaillaud/.nimble/pkgs/faststreams-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/testutils-0.4.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:/home/rcaillaud/.nimble/pkgs/chronos-3.0.11 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/bearssl-0.1.5 --path:/home/rcaillaud/.nimble/pkgs/httputils-0.3.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' --path:'/home/rcaillaud/.nimble/pkgs/unittest2-#head' 
> --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --path:/home/rcaillaud/.nimble/pkgs/stew-0.1.0 --hints:off -o:/home/rcaillaud/Workspace/localws/langserver/nimlangserver /home/rcaillaud/Workspace/localws/langserver/nimlangserver.nim
> 

This is caused because Nimble does not handle transitive dependencies and consider fork of a Nimble package as independent.
As you can see there is 2 asynctools package : the fork and the "nimble" one in the dependencies list and both are treated as separate.

The fork of asynctools need to be merged in the main nimble repository to be able to handle transitive dependencies AND/OR Nimble dependencies resolution should be fixed, specifically when using fork of nimble package.

You can work around this by modifying locally asynctools and using ``nimble develop`` but it shouldn't be considered as a practical solution because it would prevent the usage of ``asynctools`` as a nimble repo.

**Comment by yyoncho** [comment]
I will first try to get the PR in (as a side note I was unable to reproduce after `choosenim 1.6.6` and removing .nimble/pkgs)

https://github.com/cheatfate/asynctools/pull/40

**Comment by Clonkk** [comment]
> I will first try to get the PR in (as a side note I was unable to reproduce after choosenim 1.6.6 and removing .nimble/pkgs)

Strange. Maybe you have a leftover of a config file or nimble develop ?

**Comment by dom96** [comment]
It might be best to try the new Nimble lock files to resolve these kinds of issues.

**Comment by dom96** [comment]
> Does nimble lock change this behavior ?

It does not. There were some changes to how dependencies are installed but I can't say whether this would change the semantics of the situation you describe.

Indeed, there isn't much we can do here other than hope that the two packages can both relax their package requirements, and lean more on the lock files to guarantee that `https://github.com/yyoncho/asynctools#non-blocking` is used.

**Comment by Clonkk** [comment]
> Indeed, it seems there isn't much we can do here other than hope that the two packages can both relax their package requirements, and lean more on the lock files to guarantee that https://github.com/yyoncho/asynctools#non-blocking is used.

Dependency resolution is sadly a recurring issue for nimble.

See
* https://github.com/nim-lang/RFCs/issues/398
* https://github.com/nim-lang/nimble/issues/505
* https://github.com/nim-lang/nimble/issues/890

**Comment by Clonkk** [comment]
Note that solving this particular problem with local nimble develop puts in evidence another issue : 

```
   Building nimlangserver/nimlangserver using c backend
/home/rcaillaud/Workspace/localws/langserver/nimlangserver.nim(563, 57) Error: type mismatch: got <File, allowAsyncOps: bool>
but expected one of:
proc fileOutput(f: File; pageSize = defaultPageSize): OutputStreamHandle
  first type mismatch at position: 2
  unknown named parameter: allowAsyncOps
1 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: fileOutput(stdout, allowAsyncOps = true)
       Tip: 236 messages have been suppressed, use --verbose to show them.
```

Which I assume is similar in nature

**Comment by yyoncho** [comment]
@Clonkk I pushed https://github.com/yyoncho/nim-json-rpc/commit/38885260934d36ce6955a0599af1578cadaf65ec so hopefully this will fix the issue.

**Comment by Clonkk** [comment]
I retried this morning; problem seems solved.
