### ISSUE TITLE
nimlangserver crashes in vscode on Win10 : exit code 1

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/langserver#146]
in https://github.com/nim-lang/langserver/issues/92 , [nickysn](https://github.com/nickysn) improved the nimlangserver
and helped me to get the nimlangserver
working on Win10 with nim-2.0.3 🙂

EDIT on 2024-01-28 :
now the nimlangserver with nim-2.0.3 also always
crashes  with the same error as with with nim-2.1.1 :
`[Error] Server process exited with code 1`
details in the next post of this thread .

**Comment by dreamflow** [comment]
at the commit [fixed crash in getRootPath on Windows](https://github.com/nim-lang/langserver/commit/4979bb060951675ddb74a1ac1076debd3b45b44f) ,
nimlangserver.exe worked in vscode on Win10 with nim-2.0.3
-> https://github.com/nim-lang/langserver/issues/92#issuecomment-1913189575

but after redownloading/reinstalling the newest nimlangserver.exe
from "nimlangserver-windows-amd64.zip"
from https://github.com/nim-lang/langserver/releases
it stopped working with nim-2.0.3 and now crashes always
with the same error as with with nim-2.1.1 :
`[Error] Server process exited with code 1`

i also redownloaded/reinstalled nim-2.0.3
( windows amd64 , compiled at 2024-01-20 ) ,
so there something could be different
causing nimlangserver.exe to crash .

the following tests were done with the nimlangserver.exe
( compile date 2024-01-27 15:40
= "date modified" from its exe properties )
at the commit [fixed crash in getRootPath on Windows](https://github.com/nim-lang/langserver/commit/4979bb060951675ddb74a1ac1076debd3b45b44f) :

[crash.output.of.nimlangserver.with.nim-2.0.3.log](https://github.com/nim-lang/langserver/files/14076014/crash.output.of.nimlangserver.with.nim-2.0.3.log)

[crash.output.of.nimlangserver.with.nim-2.1.1.log](https://github.com/nim-lang/langserver/files/14076016/crash.output.of.nimlangserver.with.nim-2.1.1.log)

my updated current environment :
- Win10 64bit 22H2
- vscode 64bit 1.85.2
- vscode extensions "nim-lang.org" 0.8.2
- latest nimlangserver.exe
from "nimlangserver-windows-amd64.zip"
from https://github.com/nim-lang/langserver/releases

**Comment by nickysn** [comment]
Very strange! I cannot reproduce this. :(

Are you sure you have a working nimsuggest.exe in your PATH that is the same version as the Nim compiler? Is there any anti-virus or firewall software blocking the start of nimsuggest.exe?

**Comment by dreamflow** [comment]
> Are you sure you have a working nimsuggest.exe in
 > your PATH that is the same version as the Nim compiler?

yes , i always unpack them together from the downloaded
nim-2.0.3-windows_x64.zip
nim-2.1.1-windows_x64.zip
from https://github.com/nim-lang/nightlies/releases

and i checked again now , that all needed executables
are reachable via the PATH env var :

```
nimlangserver.exe --version
1.1.0
```

```
nimsuggest.exe --version
Nim Compiler Version 2.0.3 [Windows: amd64]
Compiled at 2024-01-20
```

```
nim.exe -version
Nim Compiler Version 2.0.3 [Windows: amd64]
Compiled at 2024-01-20
```

 > Is there any ... firewall software blocking the start of nimsuggest.exe?

that coud be the case , because i rember , yesterday when it worked ,
on the first run , the windows firewall window appeard and asked
to allow workplace or public network-access . by habbit i denied it ,
assuming that nimlangserver.exe and nimsuggest.exe are
communicating locally via loopback if they communicate via tcp ,
so that the windows-firewall should not interfere there .

now i tried the following :
- turned off domain-network
and private-network
- deleted all entries in the windows-firewall with names
containing "vscode" or "nimsuggest"

but it made no difference , nimlangserver.exe still crashes with
`[Error] Server process exited with code 1`

but the windows-firewall is deeper than my above actions .

is there i way to check the communication with
nimlangserver.exe and/or nimsuggest.exe ?
is it possible to send them some tcp messages ?

on my Win10 computer is no other firewall software
than the onboard windows-firewall .

 > Is there any anti-virus ... software blocking the start of nimsuggest.exe?

indeed , the windows-defender almost always wants to block
some exe's within the folder of nim.exe , after each download
and extraction of
nim-2.0.3-windows_x64.zip
nim-2.1.1-windows_x64.zip
what i always then do is to allow these exe's and then i check
if these exe's can be started .
although the windows defender is annoying about these exe's ,
at least it's easy to make sure that they are not blocked by
the windows-defender , by test running them after allowing
them in the windows-defender .

on my Win10 computer is no other antivir software
than the onboard windows-defender .

**Comment by nickysn** [comment]
Can you open a console and run nimsuggest like that:
`nimsuggest --v4 --autobind`
It should start and write a port number on standard output. This is a TCP port number. Try connecting to this port via telnet and see if that works.

**Comment by dreamflow** [comment]
> nimsuggest nimfilename.nim --v4 --autobind
 > Try connecting to this port via telnet

connecting telnet to the nimsuggest port
worked like a charm .
a nice & easy test in a problem situation .
thank you 🙂

and more good news : i have solved the problem .
to faster unpack nim-2.?.?-windows_x64.zip ,
most of the time i've extracted only the "bin/"
folder .

now i've found out that also are necessary the
file & folder "lib/system.nim" & "lib/system/" .
that is suprising , because there are only source
files and my assumption was , that the compiled
binaries nimsuggest.exe and/or nimlangserver.exe
wouldn't depend on source files after the compilation .

but it's not a problem , if simply the entire zip-file
is extracted .

i'll close this issue as successfully completed .

many thanks for your help 🙂
