### ISSUE TITLE
`compile` pragma causes crash with Kate

### ISSUE THREAD

**Issue by beef331** [nim-lang/langserver#16]
Attempted to use this LSP with Kate and a file with just`{.compile: "".} causes the following.
![image](https://user-images.githubusercontent.com/11792483/177103405-e6a170e8-caee-4d65-a38e-63bf116d8014.png)

**Comment by yyoncho** [comment]
Can you do `nimsuggest --v3 <the-file-with-compile>` and paste the output here?

**Comment by yyoncho** [comment]
I can confirm the issue. It is nimsuggest issue. I will move it to nim-lang/Nim repo later today and CC you.
