### ISSUE TITLE
zero results for signatureHelp, but only first time after ctrl+s

### ISSUE THREAD

**Issue by veksha** [nim-lang/langserver#174]
i tested signatureHelp on simple project and found a bug:
after i save my file (`ctrl+s`) - signatureHelp will not work one time (i get null data), but if i call it second time - it works correctly and shows signatures.

immediately after file saving it retrieves null data for some reason.

_Originally posted by @veksha in https://github.com/nim-lang/langserver/issues/87#issuecomment-1878078567_

> On the null data issue, it may be a NimSuggest related issue but couldnt repro it using vscode

_Originally posted by @jmgomez in https://github.com/nim-lang/langserver/issues/87#issuecomment-1881414292_
            

created this issue because reproduced in VSCode:

https://github.com/nim-lang/langserver/assets/275333/d2579473-077e-4194-9988-d37ec4c2bf41

**Comment by veksha** [comment]
hi, @jmgomez  thanks for fixing!
noticed same bug with completion (sug command). do i need to open another issue?

**Comment by jmgomez** [comment]
Hi @veksha, yes please, but on the Nim repo instead. 
Thank you!
