### ISSUE TITLE
nimlangserver isn't installed on plugin installation

### ISSUE THREAD

**Issue by s-tikhomirov** [nim-lang/langserver#185]
After installing the vscode-nim plugin in VSCode (in the "Extensions" menu), I get the following error message:

> Unable to find/install `nimlangserver`.

Apparently, `nimlangserver` was supposed to be automatically installed alongside the plugin, but failed.

Ubuntu 20.04.6 LTS, VSCode 1.86.1, Nim 2.0.2, nim-lang.org plugin v0.9.0.

![Screenshot from 2024-02-14 14-46-53](https://github.com/nim-lang/langserver/assets/7126627/2fd7bbbb-9970-4a87-9114-3e4767b29073)

**Comment by nickysn** [comment]
Better file this bug under the VS code plugin, rather than the language server:
https://github.com/nim-lang/vscode-nim/issues/new
Or maybe, add comments on this existing VS code plugin issue:
https://github.com/nim-lang/vscode-nim/issues/9
