### ISSUE TITLE
Nimsuggest initialization failed / process crashed

### ISSUE THREAD

**Issue by s-tikhomirov** [nim-lang/langserver#186]
Solving #185 , I installed `nimlangserver` manually with `nimble install nimlangserver`. The result was `Success:  nimlangserver installed successfully.`. I then re-launched VSCode and got the following two errors:

> Nimsuggest initialization for (path) failed with: Nimsuggest process crashed.

> Server failed with Nimsuggest process crashed.

![Screenshot from 2024-02-14 14-58-19](https://github.com/nim-lang/langserver/assets/7126627/cc00fe94-c4dc-442a-ae91-4f5ddcce8cac)

Ubuntu 20.04.6 LTS, VSCode 1.86.1, Nim 2.0.2, nim-lang.org plugin v0.9.0.

**Comment by jmgomez** [comment]
As a workaround one can run `./env.sh `. The NimSuggest issues are being fixed at https://github.com/nim-lang/Nim/pull/23293
