### ISSUE TITLE
Suggestion:  Check if libpcre.so library is installed during nimlangserver installation

### ISSUE THREAD

**Issue by aboisvert** [nim-lang/langserver#187]
It would be a better experience if there was a dependency check for libpcre.so library during nimlangserver installation otherwise it can lead to errors later on.

This issue relates to #84 as well as as https://github.com/nim-lang/vscode-nim/issues/43.

In the case of vscode, it can lead to mysterious/silent failure which is not obvious to diagnose since one isn't expected to run `nimlangserver` on its own and therefore the error `could not load: libpcre.so(.3|.1|)` is never shown directly to the user and the VSCode plugin just mysteriously fails activation.

**Comment by nickysn** [comment]
I've also opened a PR in the VS code extension, so the error message is shown:
https://github.com/nim-lang/vscode-nim/pull/44
Of course, we can also add dependency checks to the nimble file as well. Or do other things to ensure the dependencies are installed as well.

**Comment by arnetheduck** [comment]
Why not get rid of the pcre dependency instead? ie with https://github.com/nitely/nim-regex

**Comment by jmgomez** [comment]
Fixed by https://github.com/nim-lang/langserver/pull/259
