### ISSUE TITLE
Example vim configuration won't work with nimsuggest path

### ISSUE THREAD

**Issue by weskerfoot** [nim-lang/langserver#190]
In the readme it says to use this config

`  "nimsuggestPath": "~/.nimble/bin/nimsuggest"`

I found that it was not finding `nimsuggest` with the following error

> Unable to start nimsuggest. `~/.nimble/bin/nimsuggest` is not present on the PATH

But it was there, and when I changed it to be an expanded path it works, i.e. `/home/wes/.nimble/bin/nimsuggest`. 

Clearly something is supposed to expand that path and isn't.

**Comment by aenlemmea** [comment]
@nickysn I was able to repro this on VIM (not NVIM) with nimlangserver installed with `nimble install nimlangserver` and using coc. The fix mentioned with hardcoding the path seems to fix it, but would be helpful to know if this is WSL2 specific or not. I was running wsl2.

**Comment by nickysn** [comment]
> @nickysn I was able to repro this on VIM (not NVIM) with nimlangserver installed with `nimble install nimlangserver` and using coc. The fix mentioned with hardcoding the path seems to fix it, but would be helpful to know if this is WSL2 specific or not. I was running wsl2.

Probably not. I fixed the issue, and I don't use WSL, I use Fedora, so I could probably reproduce this under a real Linux distro. However, I don't remember the specific details, if you really won't to be 100% sure, you have to test under real Linux distros in a VM. In other words, I'm 99% sure it's not WSL specific, but if you need 100%, you need to test it. Why are you asking?
