### ISSUE TITLE
Error:  Aborting installation due to build failure.

### ISSUE THREAD

**Issue by NejatHakan** [nim-lang/langserver#191]
On my Linux Mint 21.3 machine I tried install nimlangserver as follows in my terminal:

$ nimble --verbose install nimlangserver

The result is:
###############################################################################
... many many lines .. :-))
/tmp/nimble_2040330/githubcom_nimlanglangserver/nimlangserver.nim(103, 38) Hint: ':anonymous' cannot raise 'Defect' [XCannotRaiseY]
/tmp/nimble_2040330/githubcom_nimlanglangserver/nimlangserver.nim(103, 46) Hint: ':anonymous' cannot raise 'CatchableError' [XCannotRaiseY]
/tmp/nimble_2040330/githubcom_nimlanglangserver/nimlangserver.nim(860, 6) Hint: 'expandAll' is declared but not used [XDeclaredButNotUsed]
Error: cannot open '/home/nejat/.cache/nim/nimlangserver_r/@m..@s..@s..@shome@snejat@s.nimble@spkgs2@sjson_serialization-0.2.4-74e9d9c8af0431acab7f29a4eb8ddb3d5a7ec74a@sjson_serialization@sreader_desc.nim.c'
    Prompt: Build failed for 'nimlangserver@1.2.0', would you like to try installing 'nimlangserver@#head' (latest unstable)? [y/N]

    Answer: nimble.nim(729)          install

    Error:  Aborting installation due to build failure.
     Info:  Nimble data file "/home/nejat/.nimble/nimbledata2.json" has been saved.
$ 
###############################################################################

I also tried answering the question above with "y".
It failed too.

What am I doing wrong?
Do you need any further informations?

Thank you verry much in advance for investigation.
Best regards
Yours Nejat

**Comment by NejatHakan** [comment]
Here are the version numbers of nim and nimbles if needed:

$ nim --version
Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf
...

$ nimble --version
nimble v0.14.2 compiled at 2023-12-15 01:05:41
...

**Comment by jmgomez** [comment]
Is this still an issue?
