### ISSUE TITLE
The json_rpc from chronos stops working after install nimlangserver

### ISSUE THREAD

**Issue by geohuz** [nim-lang/langserver#198]
I recently installed json_rpc from chronos and my code stop compiling after installing the nimlangserver:

```
~/.nimble/pkgs2/chronos-4.0.2-4764aff67c5f7d4cf40c3adab71a18bc26843f53/chronos/apps/http/httpserver.nim(662, 1) template/generic instantiation from here
~/.nimble/pkgs2/chronos-4.0.2-4764aff67c5f7d4cf40c3adab71a18bc26843f53/chronos/apps/http/httpserver.nim(667, 16) Error: getAcceptInfo(getString(request.headers, AcceptHeaderName, "")) can raise an unlisted exception: ref ValueError
```

**Comment by geohuz** [comment]
looks like it's a clash between yyoncho/nim-json-rpc and status/nim-json-rpc. please fix the issue

**Comment by jmgomez** [comment]
Even if we should change the dep, I dont know the reason of the fork. This is in reality a `nimble` issue. If you can still repro it, please, submit it in there.
