### ISSUE TITLE
Suggested Items in Inefficient Order

### ISSUE THREAD

**Issue by winrid** [nim-lang/langserver#214]
Hello! First off, sorry if this is in the wrong place.

I setup LSP for Nim w/ Sublime Text, however the suggested items are in a weird order:

![image](https://github.com/nim-lang/langserver/assets/1733933/46397001-cf00-41b3-83f2-46d7573a6898)

Obviously 99% of the time you'd probably want to access a property. I am not sure why `GC_ref` is the first item, but it feels very clunky/inefficient to work with. I am not sure where the issue is present, in nimsuggest, langserver, or the sublime plugin, but if anyone knows then I can redirect the issue that way. I wanted to check here before I opened an issue on Nim itself (which is where I understand nimsuggest is).

**Comment by jmgomez** [comment]
The langserver doesnt produce any suggestion, everything comes from `nimsuggest`.
