### ISSUE TITLE
crash on start in neovim

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/langserver#221]
neovim LspLog:
```
[START][2024-07-22 23:25:54] LSP logging initiated
[ERROR][2024-07-22 23:25:54] .../vim/lsp/rpc.lua:770	"rpc"	"/home/doongjohn/.nimble/bin/nimlangserver"	"stderr"	"DBG Router: dispatching                        method=initialize id=1\nDBG Initialize received...                    \nDBG Registering monitor for process            pid=14409\n"
[ERROR][2024-07-22 23:25:54] .../vim/lsp/rpc.lua:770	"rpc"	"/home/doongjohn/.nimble/bin/nimlangserver"	"stderr"	"DBG Initialize completed. Trying to start nimsuggest instances\nDBG Router: sending response                   method=initialize id=1\n"
[ERROR][2024-07-22 23:25:54] .../vim/lsp/rpc.lua:770	"rpc"	"/home/doongjohn/.nimble/bin/nimlangserver"	"stderr"	'DBG Shutting down due to an error:             msg="input(1, 0) Error: { expected"\nDBG Stack trace:                               stack_trace="parsejson.nim(518)       raiseParseErr\\n???                      start (Async)\\nasyncfutures.nim(381)    read\\n"\nShutting down due to an error: input(1, 0) Error: { expected\nparsejson.nim(518)       raiseParseErr\n???                      start (Async)\nasyncfutures.nim(381)    read\n\n'
```

neovim lsp config:
```lua
lsp.nim_langserver.setup {
  settings = {
    nim = {
      projectMapping = {
        {
          projectFile = 'tests/all.nim',
          fileRegex = 'tests/.*\\.nim'
        },
        {
          projectFile = 'main.nim',
          fileRegex = '.*\\.nim'
        },
      },
    },
  },
}
```

neovim version: `v0.10.0`
nimlangserver version: `1.4.0`

**Comment by michaelsbradleyjr** [comment]
I'm experiencing essentially the same with Emacs after building-installing `nimlangserver@#head`.

Recent changes seem to make some hard assumptions about a `.json` configuration file/s, i.e. assumptions that weren't made previously.

**Comment by jmgomez** [comment]
@doongjohn I installed `nvim` and checked it out and it does crash. However, it crashes for me in `1.2.0` as well. Can you confirm that for you it only crashes in `1.4.0`? 

BTW the issue seem to be in `fileRegex` if you remove it, it should work.

**Comment by doongjohn** [comment]
@jmgomez version 1.2.0 crashes for me as well. However removing the fileRegex doesn't seem to fix the crash.

**Comment by jmgomez** [comment]
@doongjohn can you confirm it doesnt crash for you anymore? Feel free to reopen if it does.

**Comment by doongjohn** [comment]
How can I download the master branch via nimble? It seems like nimble is keep downloading 1.4.0 even with `@#head`
![image](https://github.com/user-attachments/assets/a97db587-ce50-46e5-a830-874e61634a14)

**Comment by jmgomez** [comment]
> How can I download the master branch via nimble? It seems like nimble is keep downloading 1.4.0 even with `@#head` 

The version is not bump yet. If you want to be certain, you can clone the repro and do `nimble build` then replace the binary

**Comment by doongjohn** [comment]
@jmgomez can confirm master branch is not crashing for me.
