### ISSUE TITLE
nimlanguageserver shutting down after starting the editor with the official vs-code extension

### ISSUE THREAD

**Issue by Abathargh** [nim-lang/langserver#227]
Hi, as soon as I start coding in vscodium/code, the LSP stops working.

- nimlanguageserver version (tried with each of these options): 
  - 1.4.0 installed using `nimble install nimlanguageserver`
  - master branch built from source by cloning the repo and using `nimble build`
  - master branch built from source by cloning the repo and using `nimble build` and deleting the `nimble.lock` file to force building with the local nim version (Tried both 2.0.8 and nim devel commit c97a20ce492f335067c3e53731f60023fb39ae9d)
- Platform: x64 Linux Ubuntu 20.04
- Complete error logs:
[nimlangerror.log](https://github.com/user-attachments/files/16590091/nimlangerror.log)

Note that I don't get this error on Windows (tried with a x64 Win11 machine).

**Comment by jmgomez** [comment]
Can you retest with the latest nimlangserver from head? Also, dont delete the lock file

**Comment by Abathargh** [comment]
Still not working: tried both on vscodium and vscode on the same x64Ubuntu 20.04 machine. 
I'm attaching some pictures/logs:

[nimlangserver.log](https://github.com/user-attachments/files/16947949/nimlangserver.log)

![vscode_nim2](https://github.com/user-attachments/assets/f2005269-8ba4-4c64-95d8-0073194757ce)


![vscode_err](https://github.com/user-attachments/assets/c8408abf-cf20-4320-b636-ede937e04a3e)

**Comment by Abathargh** [comment]
This is solved, my last message was a mistake on my end using an old version
