### ISSUE TITLE
Server fails with `RecoverableError` on code with generic closures

### ISSUE THREAD

**Issue by ibb-dinosaur** [nim-lang/langserver#249]
Using VS Code with the nim-lang.org extension version: 1.2.0, nim language server version 1.6.0, Nim Compiler version 2.0.8, Windows amd64

When a file including specific code with generics and closures is opened in VSCode, the language server fails (upon restarting, it fails again)
Minimal reproducible example I could get that fails:
```nim
import sugar

type
    Parser[T] = object
    
proc eatWhile[T](p: Parser[T], predicate: T -> bool): seq[T] =
    return @[]

proc skipWs(p: Parser[char]) =
    discard p.eatWhile((c: char) => c == 'a')
```
The code is valid Nim (it compiles), so it shouldn't crash the language server.

This is the error message produced:
```
Server failed with lineinfos.nim(318)     raise RecoverableError
Error: unhandled exception: fatal error: command expects a filename [ERecoverableError]
```

**Comment by jmgomez** [comment]
Does it crash the `nimlangserver` or the `nimsuggest` instance? If the latter, please, submit the issue in the `nim` repo

**Comment by ibb-dinosaur** [comment]
`nimsuggest` actually, you're right.
