### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by lf-araujo** [nim-lang/langserver#258]
I get:

```
/tmp/nimble_30080/githubcom_nimlanglangserver_#head/utils.nim(293, 20) Warning: Use sleepAsync(Duration); sleepAsync is deprecated [Deprecated]
/tmp/nimble_30080/githubcom_nimlanglangserver_#head/ls.nim(335, 71) template/generic instantiation from here
/tmp/nimble_30080/githubcom_nimlanglangserver_#head/ls.nim(357, 32) Error: uriToPath(openFile) can raise an unlisted exception: ref ValueError
       Tip: 8 messages have been suppressed, use --verbose to show them.
nimble.nim(229)          buildFromDir

```

[luis@solus] ➜ .config nimble --version
nimble v0.14.2 compiled at 2023-10-03 01:08:07
git hash: couldn't determine git hash

[luis@solus] ➜ .config nim --version   
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-10-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 642ac0c1c31063ae966d8448c64c539203432e94
active boot switches: -d:release

What I am doing wrong?

**Comment by jmgomez** [comment]
You need `nimble > 0.16.1`
