### ISSUE TITLE
Handle nimble files

### ISSUE THREAD

**Issue by sigmaSd** [nim-lang/langserver#36]
Currently langserver seems to not handle nimble files correctly, if you open a nimble file you get many errors

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Also doesn't handle files like `config.nims` properly either (when passing commandline switches)

**Comment by ThePotatoChronicler** [comment]
You can import `system/nimscript` while writing the file, which will make it work fine in the editor, but you can't keep it there, because then it will conflict with the definitions from Nimble.

**Comment by jmgomez** [comment]
> you can import `system/nimscript` while writing the file, which will make it work fine in the editor, but you can't keep it there, because then it will conflict with the definitions from Nimble.

Try to do 

```nim
when defined(nimsuggest): 
  import system/nimscript
```

Will fix it for the next release of the langserver
