### ISSUE TITLE
Use versioned tags

### ISSUE THREAD

**Issue by daylinmorgan** [nim-lang/langserver#39]
I've opened a PR (https://github.com/mason-org/mason-registry/pull/1592) to add support for `nimlangserver` to `mason`.

Who's maintainer brought up a good point that it would be useful to have versioned releases.

**Comment by nickysn** [comment]
Using versioned tags was always the plan, we just didn't do many releases so far, due to lack of maintainers. However, this is starting to change. I've just tagged version 1.2.0:
https://github.com/nim-lang/langserver/releases/tag/v1.2.0
