### ISSUE TITLE
Segfault in 2.0.0

### ISSUE THREAD

**Issue by nettrino** [nim-lang/langserver#49]
Hello, 

I am trying to run langserver on https://github.com/crashappsec/chalk.git but getting SIGSEGV from nimsuggest on various files.

Steps to reproduce:

1. `git clone https://github.com/crashappsec/chalk.git`
2. `~/.nimble/bin/nimsuggest chalk/src/collect.nim`

This is with 
```
Nim Compiler Version 2.0.0 [MacOSX: amd64]
Compiled at 2023-09-25
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release -d:danger --gc:markAndSweep
```

**Comment by jmgomez** [comment]
The issue here seems to be in the `import` in the `config.nims`. Closing this as it is a NimSuggest issue, you can keep track of it here: https://github.com/nim-lang/langserver/issues/52#issue-1963096370
