### ISSUE TITLE
Language Server Fails after a adding specific `switch` Statement into `config.nims`

### ISSUE THREAD

**Issue by Foxicution** [nim-lang/langserver#52]
### Title
Language Server Fails after adding a specific `switch` into `config.nims`

### Description
I've encountered an issue where the Nim language server stops working upon adding a specific `switch` statement to a project's `config.nims` file. The inclusion of this line stops the language server from producing any output. Tested in Helix and VSCode.

### Steps to Reproduce
1. Create a Nim project.
2. Add a `config.nims` file in the project directory.
3. Insert the following content into `config.nims`:
    ```nim
    switch("passL", staticExec("pkg-config --libs libxml-2.0"))
    ```
4. Save the file and observe the language server's behavior (stops suggestions entirely).

### Expected Behavior
The language server should continue operating normally.

### Actual Behavior
The language server ceases to function after the addition of the specific `switch` statement in `config.nims`.

### Environment
- Nim version: 2.0.0
- Nim language server version: 0.1.0
- Operating system: NixOS 23.05 (Stoat) x86_64
- Editor/IDE: Helix, VSCode (likely others too)

**Comment by jmgomez** [comment]
This is a NimSuggest issue.
