### ISSUE TITLE
Checksum error building or installing

### ISSUE THREAD

**Issue by j0ni** [nim-lang/langserver#65]
I've encountered this same error now using Nim 2.0, and 2.1.1 (devel version) installed both via `choosenim` and directly by my package manager (Arch `pacman`/`paru`), including `choosenim` installed directly using the shell installer, and installed using `pacman`. 

Installing the langserver using `nimble`, or cloning this repo using git and attempting a `nimble build` always ends like this:

```
Downloading https://github.com/nim-lang/Nim.git using git
       Tip: 2 messages have been suppressed, use --verbose to show them.
nimble.nim(606)          downloadDependency

    Error:  Downloaded package checksum does not correspond to that in the lock file:
        ...   Package:           nim@v.2.1.1@r.940b1607b8459b4b7b7e20d316bec95c8de85809
        ...   Checksum:          265df7fa3db8a93d9ba6a89b7376a6d5346f2391
        ...   Expected checksum: ee369ca2ef4fd48e55732c09c5f8b67a4a22daa4
```
I was able to make it build by deleting the lock file and invoking `nimble lock`, but I did have to delete the lock file - contrary to the `nimble` usage output, it did not update the existing lock file.

I also wasn't able to even get `nimble` to output usage info within the project root - even with `nimble --help` it attempted to build the project and failed. I don't think that's a problem with this project though.

**Comment by jmgomez** [comment]
I dont think this is an issue anymore
