### ISSUE TITLE
"nim.provider":"lsp" deprecated

### ISSUE THREAD

**Issue by FullValueRider** [nim-lang/langserver#68]
What's going on here?
![image](https://github.com/nim-lang/langserver/assets/81257042/adaadba2-574c-4be8-8f81-a7a9350245f7)

**Comment by nickysn** [comment]
This issue belongs to the vscode-nim extension project, not the Nim language server. Reporter already opened the issue there: https://github.com/nim-lang/vscode-nim/issues/24
