### ISSUE TITLE
langserver is broken on Windows 

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/langserver#76]
Doesnt seem to work beyond startup and basic communication. Most features doesnt work at all (i.e completion, inline hints, etc.)

Update:
[x] Fix autocomplete
[ ] type inline hints

**Comment by griffith1deady** [comment]
in my case, it also consumes a very high percentage of CPU utilization. maybe this information will help.

**Comment by jmgomez** [comment]
@griffith1deady thanks, once we get some degree of stability back. We are going to look into the perf issues

**Comment by rockcavera** [comment]
In fact here it didn't work on Windows. Waiting for the correction.

**Comment by jmgomez** [comment]
@rockcavera what doesnt work for you? Are you using the source version?

**Comment by rockcavera** [comment]
> @rockcavera what doesnt work for you? Are you using the source version?

Now it worked! I installed it from #head.
