### ISSUE TITLE
infinite loop on windows

### ISSUE THREAD

**Issue by veksha** [nim-lang/langserver#78]
in `getProjectFileAutoGuess` while loop can be infinite on Windows

https://github.com/nim-lang/langserver/blob/61a13ca797c1051baab5d32fd5cdffeabfffdffc/nimlangserver.nim#L83

path will always be "D:" for example and loop never breaks.

fix:
```diff
+    if path == dir:
+      break
     path = dir
```
here: https://github.com/nim-lang/langserver/blob/61a13ca797c1051baab5d32fd5cdffeabfffdffc/nimlangserver.nim#L110

**Comment by jmgomez** [comment]
good catch!
