### ISSUE TITLE
textDocument/signatureHelp raised an exception: key not found: .context

### ISSUE THREAD

**Issue by veksha** [nim-lang/langserver#87]
hi. i get the following error when trying to get signature help:
`ResponseError[-32000]: textDocument/signatureHelp raised an exception: key not found: .context`

maybe server tries to access `context` key without checking for client capability?
(like check for `textDocument.signatureHelp.contextSupport === true` capability?)

**Comment by jmgomez** [comment]
thanks, probably your suggested fix is the way to go. What editor are you using so I can repro it?

**Comment by veksha** [comment]
CudaText editor

**Comment by jmgomez** [comment]
I couldnt setup the editor but I did add the test against the client capabilities. Please, give it a shot and let me know if it works for you by closing this issue. Thanks!

**Comment by veksha** [comment]
https://github.com/nim-lang/langserver/blob/02d304725fc0f9412f0d6e9f4a16f65d8c895d0b/nimlangserver.nim#L217-L221

As I understand, you are altering server capabilities based on the client capabilities, but i think it's not the correct way.
Maybe I wrong but server should always send its capabilities unaltered.

Instead we can try to do the next thing:
server knows that client doesn't support `context` field in SignatureHelpParams interface, so it must ignore "textDocument/signatureHelp" request and it must not try to parse it. instead it can let client know what is wrong and return response with an error message: "client doesn't support textDocument.signatureHelp.contextSupport capability".

@jmgomez , do you agree?

**Comment by jmgomez** [comment]
yes, just double checked it and you are right. We shouldnt change the server capabilities based on the client but to adjust its behaviour to it. We should do the same with the `prepareRename` above

**Comment by veksha** [comment]
i found what was causing `key not found .context`.
according to lsp spec `context` is optional for SignatureHelpParams interface.
added `Option[]` here and error is gone:

```diff
diff --git a/protocol/types.nim b/protocol/types.nim
index fb7635e..0f63cd0 100644
--- a/protocol/types.nim
+++ b/protocol/types.nim
@@ -947,7 +947,7 @@ type
     activeSignatureHelp*: Option[SignatureHelp]
 
   SignatureHelpParams* = ref object of TextDocumentPositionParams
-    context*: SignatureHelpContext
+    context*: Option[SignatureHelpContext]
 
   ExpandResult* = ref object of RootObj
     range*: Range
```

**Comment by veksha** [comment]
another thing that was stopping signatureHelp from working for me is a code that checks for `signatureHelp.contextSupport` capability :)
CudaText LSP plugin is not supporting it yet and as i see langserver not even using context for `signatureHelp`, so why we need it? 

let's remove it? it's optional and not used.

```diff
diff --git a/nimlangserver.nim b/nimlangserver.nim
index 9b724f5..eb5337d 100644
--- a/nimlangserver.nim
+++ b/nimlangserver.nim
@@ -77,7 +77,7 @@ proc partial*[A, B, C] (fn: proc(a: A, b: B, id: int): C {.gcsafe.}, a: A):
 proc supportSignatureHelp(cc: ClientCapabilities): bool = 
   if cc.isNil: return false
   let caps = cc.textDocument
-  caps.isSome and caps.get.signatureHelp.isSome and caps.get.signatureHelp.get.contextSupport.get(false)
+  caps.isSome and caps.get.signatureHelp.isSome
 
 proc getProjectFileAutoGuess(fileUri: string): string =
   let file = fileUri.decodeUrl
```

**Comment by veksha** [comment]
i tested signatureHelp on simple project and found a bug:
after i save my file (`ctrl+s`) - signatureHelp will not work one time (i get null data), but if i call it second time - it works correctly and shows signatures.

<img width="461" alt="image" src="https://github.com/nim-lang/langserver/assets/275333/52a10ccf-03c9-4423-8477-30169c449bf8">

immediately after file saving it retrieves null data for some reason.

**Comment by jmgomez** [comment]
@veksha not sure about the reasoning of making it not Optional but just changed it. On the null data issue, it may be a NimSuggest related issue but couldnt repro it using vscode

**Comment by veksha** [comment]
thanks for fixing.
