### ISSUE TITLE
nimlangserver.exe always crashes with : cannot find the path , oserrors.nim(92)

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/langserver#91]
i've installed/compiled nimlangserver via
`nimble install nimlangserver`

still in the compilation environment ,
when i run the freshly compiled `nimlangserver.exe` ,
it always crashes :
```nim
Shutting down due to an error: The system cannot find the path specified.
oserrors.nim(92)         raiseOSError
```
the same error is shown in vscode 1.85.1 by the extension [nim-lang.org](https://marketplace.visualstudio.com/items?itemName=NimLang.nimlang) ,
when it tries to run the `nimlangserver.exe` .

please help me to get the nimlangserver.exe working .

my environment :

Win10 pro 64bit 22H2

nim -v :
Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-01-14

gcc --version :
winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r3

**Comment by veksha** [comment]
`nimble install nimlangserver` - this will install latest tag.
try `nimble install nimlangserver@#head` to install latest commit

**Comment by dreamflow** [comment]
@veksha
you solved it perfectly ,
many thanks for your help 🙂

`nimlangserver.exe --version`
works now fine & shows the version .
